output() {
trap on_error ERR
